/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HomeRouteImport } from './routes/home'
import { Route as MapRouteImport } from './routes/map'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as PlacePlaceIdRouteImport } from './routes/place.$placeId'
import { Route as PlayerPlaceIdRouteImport } from './routes/player.$placeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacePlaceIdRoute = PlacePlaceIdRouteImport.update({
  id: '/place/$placeId',
  path: '/place/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlaceIdRoute = PlayerPlaceIdRouteImport.update({
  id: '/player/$placeId',
  path: '/player/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/player/$placeId': typeof PlayerPlaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/player/$placeId': typeof PlayerPlaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/challenges': typeof ChallengesRoute
  '/chat': typeof ChatRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/map': typeof MapRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/place/$placeId': typeof PlacePlaceIdRoute
  '/player/$placeId': typeof PlayerPlaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/challenges'
    | '/chat'
    | '/explore'
    | '/favorites'
    | '/home'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/voice'
    | '/place/$placeId'
    | '/player/$placeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/challenges'
    | '/chat'
    | '/explore'
    | '/favorites'
    | '/home'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/voice'
    | '/place/$placeId'
    | '/player/$placeId'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/challenges'
    | '/chat'
    | '/explore'
    | '/favorites'
    | '/home'
    | '/map'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/voice'
    | '/place/$placeId'
    | '/player/$placeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  ChallengesRoute: typeof ChallengesRoute
  ChatRoute: typeof ChatRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  MapRoute: typeof MapRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  VoiceRoute: typeof VoiceRoute
  PlacePlaceIdRoute: typeof PlacePlaceIdRoute
  PlayerPlaceIdRoute: typeof PlayerPlaceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$placeId': {
      id: '/place/$placeId'
      path: '/place/$placeId'
      fullPath: '/place/$placeId'
      preLoaderRoute: typeof PlacePlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$placeId': {
      id: '/player/$placeId'
      path: '/player/$placeId'
      fullPath: '/player/$placeId'
      preLoaderRoute: typeof PlayerPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  ChallengesRoute: ChallengesRoute,
  ChatRoute: ChatRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  MapRoute: MapRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  VoiceRoute: VoiceRoute,
  PlacePlaceIdRoute: PlacePlaceIdRoute,
  PlayerPlaceIdRoute: PlayerPlaceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
